async function PickList(username, inventoryOrgId) {
  return `SELECT DELIVERY, PICKED_BY, PROMISE_DATE, ORDER_NUMBER, DATE_SCHEDULED, ITEM_COUNT, TOTAL_ROWCOUNT, NUMBER_ROW, SO_DISPLAY, DEMAND_TYPE, ITEM_CATEGORY, CUSTOMER_NAME FROM (SELECT WDV.DELIVERY_ID DELIVERY, CASE WHEN WND.ATTRIBUTE11 IS NULL THEN 'Ready to be picked' ELSE WND.ATTRIBUTE11 END PICKED_BY, CASE WHEN WND.ATTRIBUTE11 = UPPER('${username}') THEN 1 WHEN WND.ATTRIBUTE11 <> UPPER('${username}') THEN 3 ELSE 2 END SEQ, WDV.LATEST_PICKUP_DATE PROMISE_DATE, WDV.SOURCE_HEADER_NUMBER ORDER_NUMBER, CASE WHEN COUNT(DISTINCT WDV.SOURCE_HEADER_NUMBER) OVER (PARTITION BY WDV.DELIVERY_ID) > 1 THEN 'SO# Multiple' WHEN COUNT(DISTINCT WDV.SOURCE_HEADER_NUMBER) OVER (PARTITION BY WDV.DELIVERY_ID) = 1 THEN 'SO# ' || WDV.SOURCE_HEADER_NUMBER END SO_DISPLAY, XX_DEMAND_TYPE_CATEGORY_FUNC('DEMAND', WDV.DELIVERY_ID, ${inventoryOrgId}) DEMAND_TYPE, XX_DEMAND_TYPE_CATEGORY_FUNC('CATEGORY', WDV.DELIVERY_ID, ${inventoryOrgId}) ITEM_CATEGORY, (SELECT UPPER(SUBSTR(HZP.PARTY_NAME, 1, 4)) FROM HZ_PARTIES HZP, HZ_CUST_ACCOUNTS HCA WHERE HCA.PARTY_ID = HZP.PARTY_ID AND HCA.CUST_ACCOUNT_ID = WDV.CUSTOMER_ID) CUSTOMER_NAME, DATE_SCHEDULED, COUNT(WDV.SOURCE_LINE_ID) ITEM_COUNT, ROW_NUMBER() OVER(ORDER BY WDV.DATE_SCHEDULED) ROW_NUM, WDV.CUSTOMER_ID, COUNT(*) OVER () TOTAL_ROWCOUNT, NVL((SELECT ATTRIBUTE1 FROM FND_LOOKUP_VALUES_VL FLV, XXMB_INV_ORG_V XX WHERE FLV.LOOKUP_TYPE = 'XXONT_RAD_SEG2' AND FLV.ENABLED_FLAG = 'Y' AND FLV.DESCRIPTION = XX.INV_ORG_CODE AND XX.INV_ORG_ID = ${inventoryOrgId}), 5) NUMBER_ROW FROM WSH_DELIVERABLES_V WDV, WSH_NEW_DELIVERIES WND WHERE WND.DELIVERY_ID = WDV.DELIVERY_ID AND CONTAINER_FLAG = 'N' AND SOURCE_CODE = 'OE' AND RELEASED_STATUS = 'S' AND WDV.ORGANIZATION_ID = ${inventoryOrgId} GROUP BY WDV.DELIVERY_ID, WND.ATTRIBUTE11, WDV.LATEST_PICKUP_DATE, SOURCE_HEADER_NUMBER, DATE_SCHEDULED, WDV.CUSTOMER_ID ORDER BY SEQ) WHERE ROWNUM BETWEEN 0 AND NUMBER_ROW`;
}

async function SearchBySalesOrder(sonumber, inventoryOrgId) {
  return `SELECT DISTINCT WDV.SOURCE_HEADER_NUMBER ORDER_NUMBER FROM WSH_DELIVERABLES_V WDV WHERE CONTAINER_FLAG = 'N' AND SOURCE_CODE = 'OE' AND RELEASED_STATUS = 'S' AND WDV.SOURCE_HEADER_NUMBER LIKE NVL('%'|| ${sonumber} || '%',WDV.SOURCE_HEADER_NUMBER) AND WDV.ORGANIZATION_ID = ${inventoryOrgId}`;
}

async function SearchByItemDescription(itemDescription, inventoryOrgId) {
  return `SELECT DISTINCT WDV.ITEM_DESCRIPTION FROM WSH_DELIVERABLES_V WDV WHERE CONTAINER_FLAG = 'N' AND SOURCE_CODE = 'OE' AND RELEASED_STATUS = 'S' AND WDV.ITEM_DESCRIPTION LIKE NVL('%'|| '${itemDescription}' || '%',WDV.ITEM_DESCRIPTION) AND WDV.ORGANIZATION_ID = ${inventoryOrgId}`;
}

async function SearchByDeliveryId(deliveryId, inventoryOrgId) {
  return `SELECT DISTINCT WDV.DELIVERY_ID DELIVERY FROM WSH_DELIVERABLES_V WDV WHERE CONTAINER_FLAG = 'N' AND SOURCE_CODE = 'OE' AND RELEASED_STATUS = 'S' AND WDV.DELIVERY_ID LIKE NVL('%'|| ${deliveryId} || '%',WDV.DELIVERY_ID) AND WDV.ORGANIZATION_ID = ${inventoryOrgId}`;
}

const Pick = {
  PickList,
  SearchBySalesOrder,
  SearchByItemDescription,
  SearchByDeliveryId,
};

module.exports = Pick;
